"""The VAE latent geometry of an architecture, and how to project it to a preview image.

The preview chain was never really keyed on architecture -- the branch comments in the dispatch
chain this replaces said so by hand ("Krea-2 decodes with the Qwen-Image VAE", "Z-Image uses
FLUX-compatible VAE", "Anima uses Wan 2.1 VAE"). Fifteen architectures share eight latent spaces,
and the five most recent ones introduced no new preview data at all.

Not migrated here, deliberately:

- `constants.LATENT_SCALE_FACTOR` (a module-level `8` with a live `HACK:` comment): its blast radius
  is every latent node. A follow-up, now that a correct source exists.
- `pid/decode.py`'s `_PER_BACKBONE`: same shape, different units. It describes packed latents
  (Flux2: 128 channels at 16x) where this describes VAE latents (Flux2: 32 channels at 8x). They
  are not derivable from one another.
"""

from dataclasses import dataclass

import torch
from PIL import Image

from invokeai.backend.architectures.facet import Facet
from invokeai.backend.architectures.registry import require
from invokeai.backend.model_manager.taxonomy import BaseModelType

# See scripts/generate_vae_linear_approximation.py for generating these factors.

# fast latents preview matrix for sdxl
# generated by @StAlKeR7779
SDXL_LATENT_RGB_FACTORS = [
    #   R        G        B
    [0.3816, 0.4930, 0.5320],
    [-0.3753, 0.1631, 0.1739],
    [0.1770, 0.3588, -0.2048],
    [-0.4350, -0.2644, -0.4289],
]
SDXL_SMOOTH_MATRIX = [
    [0.0358, 0.0964, 0.0358],
    [0.0964, 0.4711, 0.0964],
    [0.0358, 0.0964, 0.0358],
]

# origingally adapted from code by @erucipe and @keturn here:
# https://discuss.huggingface.co/t/decoding-latents-to-rgb-without-upscaling/23204/7
# these updated numbers for v1.5 are from @torridgristle
SD1_5_LATENT_RGB_FACTORS = [
    #    R        G        B
    [0.3444, 0.1385, 0.0670],  # L1
    [0.1247, 0.4027, 0.1494],  # L2
    [-0.3192, 0.2513, 0.2103],  # L3
    [-0.1307, -0.1874, -0.7445],  # L4
]

SD3_5_LATENT_RGB_FACTORS = [
    [-0.05240681, 0.03251581, 0.0749016],
    [-0.0580572, 0.00759826, 0.05729818],
    [0.16144888, 0.01270368, -0.03768577],
    [0.14418615, 0.08460266, 0.15941818],
    [0.04894035, 0.0056485, -0.06686988],
    [0.05187166, 0.19222395, 0.06261094],
    [0.1539433, 0.04818359, 0.07103094],
    [-0.08601796, 0.09013458, 0.10893912],
    [-0.12398469, -0.06766567, 0.0033688],
    [-0.0439737, 0.07825329, 0.02258823],
    [0.03101129, 0.06382551, 0.07753657],
    [-0.01315361, 0.08554491, -0.08772475],
    [0.06464487, 0.05914605, 0.13262741],
    [-0.07863674, -0.02261737, -0.12761454],
    [-0.09923835, -0.08010759, -0.06264447],
    [-0.03392309, -0.0804029, -0.06078822],
]

FLUX_LATENT_RGB_FACTORS = [
    [-0.0412, 0.0149, 0.0521],
    [0.0056, 0.0291, 0.0768],
    [0.0342, -0.0681, -0.0427],
    [-0.0258, 0.0092, 0.0463],
    [0.0863, 0.0784, 0.0547],
    [-0.0017, 0.0402, 0.0158],
    [0.0501, 0.1058, 0.1152],
    [-0.0209, -0.0218, -0.0329],
    [-0.0314, 0.0083, 0.0896],
    [0.0851, 0.0665, -0.0472],
    [-0.0534, 0.0238, -0.0024],
    [0.0452, -0.0026, 0.0048],
    [0.0892, 0.0831, 0.0881],
    [-0.1117, -0.0304, -0.0789],
    [0.0027, -0.0479, -0.0043],
    [-0.1146, -0.0827, -0.0598],
]

COGVIEW4_LATENT_RGB_FACTORS = [
    [0.00408832, -0.00082485, -0.00214816],
    [0.00084172, 0.00132241, 0.00842067],
    [-0.00466737, -0.00983181, -0.00699561],
    [0.03698397, -0.04797235, 0.03585809],
    [0.00234701, -0.00124326, 0.00080869],
    [-0.00723903, -0.00388422, -0.00656606],
    [-0.00970917, -0.00467356, -0.00971113],
    [0.17292486, -0.03452463, -0.1457515],
    [0.02330308, 0.02942557, 0.02704329],
    [-0.00903131, -0.01499841, -0.01432564],
    [0.01250298, 0.0019407, -0.02168986],
    [0.01371188, 0.00498283, -0.01302135],
    [0.42396525, 0.4280575, 0.42148206],
    [0.00983825, 0.00613302, 0.00610316],
    [0.00473307, -0.00889551, -0.00915924],
    [-0.00955853, -0.00980067, -0.00977842],
]

# The 16-channel Wan 2.1 VAE, shared by Qwen-Image, Krea-2 (which decodes with the Qwen-Image VAE),
# Anima, and Wan 2.2 A14B. Before the registry these numbers were written out three times, as
# QWEN_IMAGE_/ANIMA_/WAN_LATENT_RGB_FACTORS; they were byte-identical, as were the three biases.
# Factors from ComfyUI's Wan21 latent_format:
# https://github.com/comfyanonymous/ComfyUI/blob/master/comfy/latent_formats.py
WAN21_LATENT_RGB_FACTORS = [
    [-0.1299, -0.1692, 0.2932],
    [0.0671, 0.0406, 0.0442],
    [0.3568, 0.2548, 0.1747],
    [0.0372, 0.2344, 0.1420],
    [0.0313, 0.0189, -0.0328],
    [0.0296, -0.0956, -0.0665],
    [-0.3477, -0.4059, -0.2925],
    [0.0166, 0.1902, 0.1975],
    [-0.0412, 0.0267, -0.1364],
    [-0.1293, 0.0740, 0.1636],
    [0.0680, 0.3019, 0.1128],
    [0.0032, 0.0581, 0.0639],
    [-0.1251, 0.0927, 0.1699],
    [0.0060, -0.0633, 0.0005],
    [0.3477, 0.2275, 0.2950],
    [0.1984, 0.0913, 0.1861],
]

WAN21_LATENT_RGB_BIAS = [-0.1835, -0.0868, -0.3360]

# FLUX.2 uses 32 latent channels.
# Factors from ComfyUI: https://github.com/Comfy-Org/ComfyUI/blob/main/comfy/latent_formats.py
FLUX2_LATENT_RGB_FACTORS = [
    #   R        G        B
    [0.0058, 0.0113, 0.0073],
    [0.0495, 0.0443, 0.0836],
    [-0.0099, 0.0096, 0.0644],
    [0.2144, 0.3009, 0.3652],
    [0.0166, -0.0039, -0.0054],
    [0.0157, 0.0103, -0.0160],
    [-0.0398, 0.0902, -0.0235],
    [-0.0052, 0.0095, 0.0109],
    [-0.3527, -0.2712, -0.1666],
    [-0.0301, -0.0356, -0.0180],
    [-0.0107, 0.0078, 0.0013],
    [0.0746, 0.0090, -0.0941],
    [0.0156, 0.0169, 0.0070],
    [-0.0034, -0.0040, -0.0114],
    [0.0032, 0.0181, 0.0080],
    [-0.0939, -0.0008, 0.0186],
    [0.0018, 0.0043, 0.0104],
    [0.0284, 0.0056, -0.0127],
    [-0.0024, -0.0022, -0.0030],
    [0.1207, -0.0026, 0.0065],
    [0.0128, 0.0101, 0.0142],
    [0.0137, -0.0072, -0.0007],
    [0.0095, 0.0092, -0.0059],
    [0.0000, -0.0077, -0.0049],
    [-0.0465, -0.0204, -0.0312],
    [0.0095, 0.0012, -0.0066],
    [0.0290, -0.0034, 0.0025],
    [0.0220, 0.0169, -0.0048],
    [-0.0332, -0.0457, -0.0468],
    [-0.0085, 0.0389, 0.0609],
    [-0.0076, 0.0003, -0.0043],
    [-0.0111, -0.0460, -0.0614],
]

FLUX2_LATENT_RGB_BIAS = [-0.0329, -0.0718, -0.0851]

# Wan 2.2 TI2V-5B uses Wan2.2-VAE with 48 latent channels and 16x spatial downscale.
# Factors come from ComfyUI's Wan22 latent_format.
WAN22_LATENT_RGB_FACTORS = [
    [0.0119, 0.0103, 0.0046],
    [-0.1062, -0.0504, 0.0165],
    [0.0140, 0.0409, 0.0491],
    [-0.0813, -0.0677, 0.0607],
    [0.0656, 0.0851, 0.0808],
    [0.0264, 0.0463, 0.0912],
    [0.0295, 0.0326, 0.0590],
    [-0.0244, -0.0270, 0.0025],
    [0.0443, -0.0102, 0.0288],
    [-0.0465, -0.0090, -0.0205],
    [0.0359, 0.0236, 0.0082],
    [-0.0776, 0.0854, 0.1048],
    [0.0564, 0.0264, 0.0561],
    [0.0006, 0.0594, 0.0418],
    [-0.0319, -0.0542, -0.0637],
    [-0.0268, 0.0024, 0.0260],
    [0.0539, 0.0265, 0.0358],
    [-0.0359, -0.0312, -0.0287],
    [-0.0285, -0.1032, -0.1237],
    [0.1041, 0.0537, 0.0622],
    [-0.0086, -0.0374, -0.0051],
    [0.0390, 0.0670, 0.2863],
    [0.0069, 0.0144, 0.0082],
    [0.0006, -0.0167, 0.0079],
    [0.0313, -0.0574, -0.0232],
    [-0.1454, -0.0902, -0.0481],
    [0.0714, 0.0827, 0.0447],
    [-0.0304, -0.0574, -0.0196],
    [0.0401, 0.0384, 0.0204],
    [-0.0758, -0.0297, -0.0014],
    [0.0568, 0.1307, 0.1372],
    [-0.0055, -0.0310, -0.0380],
    [0.0239, -0.0305, 0.0325],
    [-0.0663, -0.0673, -0.0140],
    [-0.0416, -0.0047, -0.0023],
    [0.0166, 0.0112, -0.0093],
    [-0.0211, 0.0011, 0.0331],
    [0.1833, 0.1466, 0.2250],
    [-0.0368, 0.0370, 0.0295],
    [-0.3441, -0.3543, -0.2008],
    [-0.0479, -0.0489, -0.0420],
    [-0.0660, -0.0153, 0.0800],
    [-0.0101, 0.0068, 0.0156],
    [-0.0690, -0.0452, -0.0927],
    [-0.0145, 0.0041, 0.0015],
    [0.0421, 0.0451, 0.0373],
    [0.0504, -0.0483, -0.0356],
    [-0.0837, 0.0168, 0.0055],
]

WAN22_LATENT_RGB_BIAS = [0.0317, -0.0878, -0.1388]


def sample_to_lowres_estimated_image(
    samples: torch.Tensor,
    latent_rgb_factors: torch.Tensor,
    smooth_matrix: torch.Tensor | None = None,
    latent_rgb_bias: torch.Tensor | None = None,
) -> Image.Image:
    if samples.dim() == 4:
        samples = samples[0]
    latent_image = samples.permute(1, 2, 0) @ latent_rgb_factors

    if latent_rgb_bias is not None:
        latent_image = latent_image + latent_rgb_bias

    if smooth_matrix is not None:
        latent_image = latent_image.unsqueeze(0).permute(3, 0, 1, 2)
        latent_image = torch.nn.functional.conv2d(latent_image, smooth_matrix.reshape((1, 1, 3, 3)), padding=1)
        latent_image = latent_image.permute(1, 2, 3, 0).squeeze(0)

    latents_ubyte = (
        ((latent_image + 1) / 2).clamp(0, 1).mul(0xFF).byte()  # change scale from -1..1 to 0..1  # to 0..255
    ).cpu()

    return Image.fromarray(latents_ubyte.numpy())


@dataclass(frozen=True)
class LatentSpace:
    """One VAE latent geometry, and the linear projection that turns it into a preview image."""

    name: str
    """Stable identifier. Used in diagnostics and to keep the closed set closed in tests."""

    channels: int
    """Latent channel count. Also how `LatentSpaceFacet` tells its latent spaces apart at runtime."""

    spatial_compression: int
    """Image pixels per latent pixel, per axis. 8 everywhere except Wan's Wan2.2-VAE."""

    rgb_factors: list[list[float]]
    """A `channels` x 3 linear projection from latent space to RGB."""

    rgb_bias: list[float] | None = None
    smooth_matrix: list[list[float]] | None = None

    def __post_init__(self) -> None:
        if len(self.rgb_factors) != self.channels:
            raise ValueError(
                f"{self.name}: declares {self.channels} channels but carries {len(self.rgb_factors)} rgb_factors rows."
            )

    def preview(self, sample: torch.Tensor) -> Image.Image:
        """Project `sample` to a preview image at *latent* resolution.

        The caller scales the result by `spatial_compression` to get the image-space size. Keeping
        this a method rather than a bare factor matrix means an architecture that eventually needs a
        real tiny-VAE decode is not forced through a linear projection.
        """
        return sample_to_lowres_estimated_image(
            samples=sample,
            latent_rgb_factors=torch.tensor(self.rgb_factors, dtype=sample.dtype, device=sample.device),
            smooth_matrix=(
                torch.tensor(self.smooth_matrix, dtype=sample.dtype, device=sample.device)
                if self.smooth_matrix
                else None
            ),
            latent_rgb_bias=(
                torch.tensor(self.rgb_bias, dtype=sample.dtype, device=sample.device) if self.rgb_bias else None
            ),
        )


SD15_4 = LatentSpace(name="SD15_4", channels=4, spatial_compression=8, rgb_factors=SD1_5_LATENT_RGB_FACTORS)

SDXL_4 = LatentSpace(
    name="SDXL_4",
    channels=4,
    spatial_compression=8,
    rgb_factors=SDXL_LATENT_RGB_FACTORS,
    smooth_matrix=SDXL_SMOOTH_MATRIX,
)

SD3_16 = LatentSpace(name="SD3_16", channels=16, spatial_compression=8, rgb_factors=SD3_5_LATENT_RGB_FACTORS)

COGVIEW4_16 = LatentSpace(
    name="COGVIEW4_16", channels=16, spatial_compression=8, rgb_factors=COGVIEW4_LATENT_RGB_FACTORS
)

FLUX_16 = LatentSpace(name="FLUX_16", channels=16, spatial_compression=8, rgb_factors=FLUX_LATENT_RGB_FACTORS)

WAN21_16 = LatentSpace(
    name="WAN21_16",
    channels=16,
    spatial_compression=8,
    rgb_factors=WAN21_LATENT_RGB_FACTORS,
    rgb_bias=WAN21_LATENT_RGB_BIAS,
)

# The FLUX.2 VAE is 16x on packed latents, but every denoise loop that reaches a preview unpacks
# first, so in the units this class uses it is 8x. Do not "correct" this to 16.
FLUX2_32 = LatentSpace(
    name="FLUX2_32",
    channels=32,
    spatial_compression=8,
    rgb_factors=FLUX2_LATENT_RGB_FACTORS,
    rgb_bias=FLUX2_LATENT_RGB_BIAS,
)

WAN22_48 = LatentSpace(
    name="WAN22_48",
    channels=48,
    spatial_compression=16,
    rgb_factors=WAN22_LATENT_RGB_FACTORS,
    rgb_bias=WAN22_LATENT_RGB_BIAS,
)


@dataclass(frozen=True)
class LatentSpaceFacet(Facet):
    """The latent space, or spaces, an architecture denoises in."""

    REQUIRED = True

    default: LatentSpace

    alternates: tuple[LatentSpace, ...] = ()
    """Further latent spaces this architecture may denoise in, told apart at runtime by the sample's
    channel count. Only Wan has any: A14B uses the 16-channel Wan 2.1 VAE, TI2V-5B the 48-channel
    Wan2.2-VAE, and before the registry the code picked between them by hand -- in two places, once
    for the factors and once for the spatial scale, which is exactly how those two could drift."""

    def __post_init__(self) -> None:
        channels = [latent_space.channels for latent_space in (self.default, *self.alternates)]
        if len(set(channels)) != len(channels):
            raise ValueError(
                f"{self.default.name}: latent spaces are selected by channel count, so no two may share one "
                f"(got {channels})."
            )

    def resolve(self, sample: torch.Tensor) -> LatentSpace:
        """The latent space matching `sample`'s channel count.

        An architecture with a single latent space returns it without inspecting the sample at all.
        That preserves the pre-registry behaviour: only the Wan branch ever read `sample.shape[-3]`,
        so an unusually shaped sample must not start raising IndexError for the other fourteen.
        """
        if not self.alternates:
            return self.default
        channels = sample.shape[-3]
        for latent_space in self.alternates:
            if latent_space.channels == channels:
                return latent_space
        return self.default


def get_latent_space(base: BaseModelType) -> LatentSpace:
    """The latent space `base` denoises in; for the one architecture with several, its default.

    Use this where no sample is available yet -- to hoist the projection out of a per-step closure,
    for instance. Use `resolve_latent_space()` where there is a sample.
    """
    return require(base, LatentSpaceFacet).default


def resolve_latent_space(base: BaseModelType, sample: torch.Tensor) -> LatentSpace:
    """The latent space `base` denoises in, disambiguated by `sample` where it has more than one."""
    return require(base, LatentSpaceFacet).resolve(sample)
