"""The starter-model catalog.

The entries themselves live one module per architecture; this module holds what cannot be derived
from them:

- `STARTER_MODELS`, whose order is what the model manager shows. It follows neither base nor model
  type nor definition order -- 179 entries in 47 runs by base -- so it is curated data, not a
  structural property, and concatenating the per-architecture modules would silently reorder the UI.
- `STARTER_BUNDLES`, whose keys are `BaseModelType` for ten bundles and the plain strings
  `"wan_t2v"` / `"wan_i2v"` for the other two. Kept exactly as they are: they are serialised into
  the API response.

Every entry is re-exported here, so existing imports of individual models keep working.
"""

from invokeai.backend.model_manager.starter_models.anima import (
    anima_base,
    anima_lllite_depth_preview3,
    anima_lllite_inpainting,
    anima_lllite_lineart_preview3,
    anima_lllite_pose_preview3,
    anima_lllite_scribble_preview3,
    anima_lllite_sketch,
    anima_vae,
)
from invokeai.backend.model_manager.starter_models.cogview4 import (
    cogview4,
)
from invokeai.backend.model_manager.starter_models.common import (
    anima_qwen3_encoder,
    animesharp_v4_rcan,
    clip_l_encoder,
    clip_vit_l_image_encoder,
    esrgan_srx4,
    flux2_klein_qwen3_4b_encoder,
    flux2_klein_qwen3_8b_encoder,
    flux_vae,
    gemma2_2b_encoder,
    ip_adapter_sd_image_encoder,
    ip_adapter_sdxl_image_encoder,
    llava_onevision,
    llava_onevision_7b,
    qwen2_5_1_5b_instruct,
    qwen2_5_3b_instruct,
    qwen3_vl_encoder_4b,
    qwen_image_vae,
    qwen_vl_encoder_diffusers,
    qwen_vl_encoder_fp8,
    realesrgan_x2,
    realesrgan_x4,
    sdxl_fp16_vae_fix,
    siglip,
    smollm2_1_7b_instruct,
    swinir,
    t5_8b_quantized_encoder,
    t5_base_encoder,
    t5_gguf_q3_k_s_encoder,
    t5_gguf_q6_k_encoder,
    wan_22_t5_encoder,
    z_image_qwen3_encoder,
    z_image_qwen3_encoder_quantized,
)
from invokeai.backend.model_manager.starter_models.ernie_image import (
    ernie_image,
    ernie_image_turbo,
)
from invokeai.backend.model_manager.starter_models.external import (
    alibabacloud_qwen_image_2,
    alibabacloud_qwen_image_2_pro,
    alibabacloud_qwen_image_edit_max,
    alibabacloud_qwen_image_max,
    alibabacloud_wan26_t2i,
    gemini_3_1_flash_image_preview,
    gemini_flash_image,
    gemini_pro_image_preview,
    openai_dall_e_3,
    openai_gpt_image_1,
    openai_gpt_image_1_5,
    openai_gpt_image_1_mini,
    openai_gpt_image_2,
    seedream_4_0,
    seedream_4_5,
    seedream_5_0,
    seedream_5_0_lite,
)
from invokeai.backend.model_manager.starter_models.flux import (
    flux_canny_control_lora,
    flux_depth_control_lora,
    flux_dev,
    flux_dev_quantized,
    flux_fill,
    flux_kontext,
    flux_kontext_quantized,
    flux_krea,
    flux_krea_quantized,
    flux_redux,
    flux_schnell,
    flux_schnell_quantized,
    ip_adapter_flux,
    pid_decoder_flux_2k,
    pid_decoder_flux_2kto4k,
    union_cnet_flux,
)
from invokeai.backend.model_manager.starter_models.flux2 import (
    flux2_klein_4b,
    flux2_klein_4b_fp8,
    flux2_klein_4b_gguf_q4,
    flux2_klein_4b_gguf_q8,
    flux2_klein_4b_single,
    flux2_klein_9b,
    flux2_klein_9b_fp8,
    flux2_klein_9b_gguf_q4,
    flux2_klein_9b_gguf_q8,
    flux2_vae,
    pid_decoder_flux2_2k,
    pid_decoder_flux2_2kto4k,
)
from invokeai.backend.model_manager.starter_models.ideogram_4 import (
    ideogram_4_fp8,
    ideogram_4_nf4,
)
from invokeai.backend.model_manager.starter_models.krea_2 import (
    krea2_raw,
    krea2_turbo,
    krea2_turbo_gguf_q4_k_m,
    krea2_turbo_gguf_q8_0,
)
from invokeai.backend.model_manager.starter_models.qwen_image import (
    pid_decoder_qwenimage_2kto4k,
    qwen_image,
    qwen_image_edit,
    qwen_image_edit_gguf_q2_k,
    qwen_image_edit_gguf_q4_k_m,
    qwen_image_edit_gguf_q6_k,
    qwen_image_edit_gguf_q8_0,
    qwen_image_edit_lightning_4step,
    qwen_image_edit_lightning_8step,
    qwen_image_gguf_q2_k,
    qwen_image_gguf_q4_k_m,
    qwen_image_gguf_q6_k,
    qwen_image_gguf_q8_0,
    qwen_image_lightning_4step,
    qwen_image_lightning_8step,
)
from invokeai.backend.model_manager.starter_models.sd_1 import (
    canny_sd1,
    cyberrealistic_negative,
    cyberrealistic_sd1,
    deliberate_inpainting_sd1,
    deliberate_sd1,
    depth_sd1,
    dreamshaper_8_inpainting_sd1,
    dreamshaper_8_sd1,
    easy_neg_sd1,
    inpaint_cnet_sd1,
    ip_adapter_plus_face_sd1,
    ip_adapter_plus_sd1,
    ip_adapter_sd1,
    lineart_anime_sd1,
    lineart_sd1,
    mlsd_sd1,
    normal_bae_sd1,
    openpose_sd1,
    qr_code_cnet_sd1,
    rev_animated_sd1,
    scribble_sd1,
    seg_sd1,
    shuffle_sd1,
    softedge_sd1,
    t2i_canny_sd1,
    t2i_depth_sd1,
    t2i_sketch_sd1,
    tile_sd1,
)
from invokeai.backend.model_manager.starter_models.sd_3 import (
    pid_decoder_sd3_2k,
    pid_decoder_sd3_2kto4k,
    sd35_large,
    sd35_medium,
)
from invokeai.backend.model_manager.starter_models.sdxl import (
    alien_lora_sdxl,
    archvis_sdxl,
    canny_sdxl,
    depth_sdxl,
    dreamshaper_sdxl,
    ip_adapter_plus_sdxl,
    ip_adapter_sdxl,
    juggernaut_sdxl,
    noodle_lora_sdxl,
    openpose_sdxl,
    pid_decoder_sdxl_2kto4k,
    qr_code_cnet_sdxl,
    scribble_sdxl,
    softedge_sdxl,
    t2i_canny_sdxl,
    t2i_lineart_sdxl,
    t2i_sketch_sdxl,
    tile_sdxl,
    union_cnet_sdxl,
)
from invokeai.backend.model_manager.starter_models.sdxl_refiner import (
    sdxl_refiner,
)
from invokeai.backend.model_manager.starter_models.types import (
    StarterModel,
    StarterModelBundle,
    StarterModelWithoutDependencies,
)
from invokeai.backend.model_manager.starter_models.wan import (
    wan_22_5b_vae,
    wan_22_a14b_vae,
    wan_22_i2v_a14b_diffusers,
    wan_22_i2v_a14b_gguf_q4_k_m,
    wan_22_i2v_a14b_gguf_q8_0,
    wan_22_i2v_a14b_low_gguf_q4_k_m,
    wan_22_i2v_a14b_low_gguf_q8_0,
    wan_22_i2v_lightning_high,
    wan_22_i2v_lightning_low,
    wan_22_t2v_a14b_diffusers,
    wan_22_t2v_a14b_gguf_q4_k_m,
    wan_22_t2v_a14b_gguf_q8_0,
    wan_22_t2v_a14b_low_gguf_q4_k_m,
    wan_22_t2v_a14b_low_gguf_q8_0,
    wan_22_t2v_lightning_high,
    wan_22_t2v_lightning_low,
    wan_22_ti2v_5b_diffusers,
    wan_22_ti2v_5b_gguf_q4_k_m,
    wan_22_ti2v_5b_gguf_q8_0,
)
from invokeai.backend.model_manager.starter_models.z_image import (
    z_image_controlnet_tile,
    z_image_controlnet_union,
    z_image_turbo,
    z_image_turbo_q8,
    z_image_turbo_quantized,
)
from invokeai.backend.model_manager.taxonomy import BaseModelType

# List of starter models, displayed on the frontend.
# The order/sort of this list is not changed by the frontend - set it how you want it here.
STARTER_MODELS: list[StarterModel] = [
    flux_kontext_quantized,
    flux_schnell_quantized,
    flux_dev_quantized,
    flux_schnell,
    flux_dev,
    sd35_medium,
    sd35_large,
    ideogram_4_nf4,
    ideogram_4_fp8,
    cyberrealistic_sd1,
    rev_animated_sd1,
    dreamshaper_8_sd1,
    dreamshaper_8_inpainting_sd1,
    deliberate_sd1,
    deliberate_inpainting_sd1,
    juggernaut_sdxl,
    dreamshaper_sdxl,
    archvis_sdxl,
    sdxl_refiner,
    sdxl_fp16_vae_fix,
    flux_vae,
    alien_lora_sdxl,
    noodle_lora_sdxl,
    easy_neg_sd1,
    ip_adapter_sd1,
    ip_adapter_plus_sd1,
    ip_adapter_plus_face_sd1,
    ip_adapter_sdxl,
    ip_adapter_plus_sdxl,
    ip_adapter_flux,
    qr_code_cnet_sd1,
    qr_code_cnet_sdxl,
    canny_sd1,
    inpaint_cnet_sd1,
    mlsd_sd1,
    depth_sd1,
    normal_bae_sd1,
    seg_sd1,
    lineart_sd1,
    lineart_anime_sd1,
    openpose_sd1,
    scribble_sd1,
    softedge_sd1,
    shuffle_sd1,
    tile_sd1,
    canny_sdxl,
    depth_sdxl,
    softedge_sdxl,
    openpose_sdxl,
    scribble_sdxl,
    tile_sdxl,
    union_cnet_sdxl,
    union_cnet_flux,
    flux_canny_control_lora,
    flux_depth_control_lora,
    t2i_canny_sd1,
    t2i_sketch_sd1,
    t2i_depth_sd1,
    t2i_canny_sdxl,
    t2i_lineart_sdxl,
    t2i_sketch_sdxl,
    realesrgan_x4,
    animesharp_v4_rcan,
    realesrgan_x2,
    swinir,
    t5_base_encoder,
    t5_8b_quantized_encoder,
    t5_gguf_q3_k_s_encoder,
    t5_gguf_q6_k_encoder,
    clip_l_encoder,
    siglip,
    flux_redux,
    llava_onevision,
    llava_onevision_7b,
    qwen2_5_1_5b_instruct,
    qwen2_5_3b_instruct,
    smollm2_1_7b_instruct,
    flux_fill,
    flux2_vae,
    flux2_klein_4b,
    flux2_klein_4b_single,
    flux2_klein_4b_fp8,
    flux2_klein_9b,
    flux2_klein_9b_fp8,
    flux2_klein_4b_gguf_q4,
    flux2_klein_4b_gguf_q8,
    flux2_klein_9b_gguf_q4,
    flux2_klein_9b_gguf_q8,
    flux2_klein_qwen3_4b_encoder,
    flux2_klein_qwen3_8b_encoder,
    cogview4,
    qwen_image_vae,
    qwen_vl_encoder_fp8,
    qwen_vl_encoder_diffusers,
    qwen_image_edit,
    qwen_image_edit_gguf_q2_k,
    qwen_image_edit_gguf_q4_k_m,
    qwen_image_edit_gguf_q6_k,
    qwen_image_edit_gguf_q8_0,
    qwen_image_edit_lightning_4step,
    qwen_image_edit_lightning_8step,
    qwen_image,
    qwen_image_gguf_q2_k,
    qwen_image_gguf_q4_k_m,
    qwen_image_gguf_q6_k,
    qwen_image_gguf_q8_0,
    qwen_image_lightning_4step,
    qwen_image_lightning_8step,
    flux_krea,
    flux_krea_quantized,
    z_image_turbo,
    z_image_turbo_quantized,
    z_image_turbo_q8,
    z_image_qwen3_encoder,
    z_image_qwen3_encoder_quantized,
    z_image_controlnet_union,
    z_image_controlnet_tile,
    ernie_image,
    ernie_image_turbo,
    krea2_turbo,
    krea2_raw,
    krea2_turbo_gguf_q4_k_m,
    krea2_turbo_gguf_q8_0,
    qwen3_vl_encoder_4b,
    wan_22_t5_encoder,
    wan_22_a14b_vae,
    wan_22_5b_vae,
    wan_22_t2v_a14b_diffusers,
    wan_22_t2v_a14b_low_gguf_q4_k_m,
    wan_22_t2v_a14b_gguf_q4_k_m,
    wan_22_t2v_a14b_low_gguf_q8_0,
    wan_22_t2v_a14b_gguf_q8_0,
    wan_22_t2v_lightning_high,
    wan_22_t2v_lightning_low,
    wan_22_i2v_a14b_diffusers,
    wan_22_i2v_a14b_low_gguf_q4_k_m,
    wan_22_i2v_a14b_gguf_q4_k_m,
    wan_22_i2v_a14b_low_gguf_q8_0,
    wan_22_i2v_a14b_gguf_q8_0,
    wan_22_i2v_lightning_high,
    wan_22_i2v_lightning_low,
    wan_22_ti2v_5b_diffusers,
    wan_22_ti2v_5b_gguf_q4_k_m,
    wan_22_ti2v_5b_gguf_q8_0,
    gemini_flash_image,
    gemini_pro_image_preview,
    gemini_3_1_flash_image_preview,
    openai_gpt_image_2,
    openai_gpt_image_1_5,
    openai_gpt_image_1,
    openai_gpt_image_1_mini,
    openai_dall_e_3,
    seedream_5_0,
    seedream_5_0_lite,
    seedream_4_5,
    seedream_4_0,
    alibabacloud_qwen_image_2_pro,
    alibabacloud_qwen_image_2,
    alibabacloud_qwen_image_max,
    alibabacloud_wan26_t2i,
    alibabacloud_qwen_image_edit_max,
    anima_base,
    anima_qwen3_encoder,
    anima_vae,
    anima_lllite_inpainting,
    anima_lllite_sketch,
    anima_lllite_depth_preview3,
    anima_lllite_scribble_preview3,
    anima_lllite_lineart_preview3,
    anima_lllite_pose_preview3,
    gemma2_2b_encoder,
    pid_decoder_flux_2k,
    pid_decoder_flux_2kto4k,
    pid_decoder_flux2_2k,
    pid_decoder_flux2_2kto4k,
    pid_decoder_sd3_2k,
    pid_decoder_sd3_2kto4k,
    pid_decoder_sdxl_2kto4k,
    pid_decoder_qwenimage_2kto4k,
]


sd1_bundle: list[StarterModel] = [
    dreamshaper_8_sd1,
    easy_neg_sd1,
    ip_adapter_sd1,
    ip_adapter_plus_sd1,
    ip_adapter_plus_face_sd1,
    canny_sd1,
    inpaint_cnet_sd1,
    mlsd_sd1,
    depth_sd1,
    normal_bae_sd1,
    seg_sd1,
    lineart_sd1,
    lineart_anime_sd1,
    openpose_sd1,
    scribble_sd1,
    softedge_sd1,
    shuffle_sd1,
    tile_sd1,
    swinir,
]


sdxl_bundle: list[StarterModel] = [
    juggernaut_sdxl,
    sdxl_fp16_vae_fix,
    ip_adapter_sdxl,
    ip_adapter_plus_sdxl,
    canny_sdxl,
    depth_sdxl,
    softedge_sdxl,
    openpose_sdxl,
    scribble_sdxl,
    tile_sdxl,
    swinir,
]


flux_bundle: list[StarterModel] = [
    flux_schnell_quantized,
    flux_dev_quantized,
    flux_vae,
    t5_8b_quantized_encoder,
    clip_l_encoder,
    union_cnet_flux,
    ip_adapter_flux,
    flux_canny_control_lora,
    flux_depth_control_lora,
    flux_redux,
    flux_fill,
    flux_kontext_quantized,
    flux_krea_quantized,
]


zimage_bundle: list[StarterModel] = [
    z_image_turbo_quantized,
    z_image_qwen3_encoder_quantized,
    z_image_controlnet_union,
    z_image_controlnet_tile,
    flux_vae,
]


flux2_klein_bundle: list[StarterModel] = [
    flux2_klein_4b_gguf_q4,
    flux2_vae,
    flux2_klein_qwen3_4b_encoder,
]


# Turbo only: both checkpoints are 8B and the full pipeline is a large download, so the bundle
# ships the fast default. The undistilled `ernie_image` is still installable individually.
ernie_image_bundle: list[StarterModel] = [
    ernie_image_turbo,
]


qwen_image_bundle: list[StarterModel] = [
    qwen_image_vae,
    qwen_vl_encoder_fp8,
    qwen_image_edit,
    qwen_image_edit_gguf_q4_k_m,
    qwen_image_edit_gguf_q8_0,
    qwen_image_edit_lightning_4step,
    qwen_image_edit_lightning_8step,
    qwen_image,
    qwen_image_gguf_q4_k_m,
    qwen_image_gguf_q8_0,
    qwen_image_lightning_4step,
    qwen_image_lightning_8step,
]


anima_bundle: list[StarterModel] = [
    anima_base,
    anima_qwen3_encoder,
    anima_vae,
    anima_lllite_inpainting,
    anima_lllite_sketch,
]


krea2_bundle: list[StarterModel] = [
    qwen_image_vae,
    qwen3_vl_encoder_4b,
    krea2_turbo,
    krea2_raw,
    krea2_turbo_gguf_q4_k_m,
    krea2_turbo_gguf_q8_0,
]


# Wan 2.2 starter bundles. Split into T2V and I2V so users only pay for the
# capability they need: a 12 GB card can install just the T2V bundle and have
# both text-to-video (T2V-A14B) and a low-VRAM image-to-video option (via
# TI2V-5B, which handles both modes in one ~3.4 GB model). The I2V bundle adds
# the heavier I2V-A14B path for users with more headroom. Q8 variants and full
# Diffusers builds stay available as a-la-carte starters.
wan_t2v_bundle: list[StarterModel] = [
    wan_22_t5_encoder,
    wan_22_a14b_vae,
    wan_22_5b_vae,
    wan_22_ti2v_5b_gguf_q4_k_m,
    wan_22_t2v_a14b_gguf_q4_k_m,
    wan_22_t2v_a14b_low_gguf_q4_k_m,
    wan_22_t2v_lightning_high,
    wan_22_t2v_lightning_low,
]


wan_i2v_bundle: list[StarterModel] = [
    wan_22_t5_encoder,
    wan_22_a14b_vae,
    wan_22_i2v_a14b_gguf_q4_k_m,
    wan_22_i2v_a14b_low_gguf_q4_k_m,
    wan_22_i2v_lightning_high,
    wan_22_i2v_lightning_low,
]


# nf4 is the recommended 24GB CUDA path; the fp8 build is offered separately for non-CUDA / more VRAM.
ideogram_bundle: list[StarterModel] = [
    ideogram_4_nf4,
]


STARTER_BUNDLES: dict[str, StarterModelBundle] = {
    BaseModelType.StableDiffusion1: StarterModelBundle(name="Stable Diffusion 1.5", models=sd1_bundle),
    BaseModelType.StableDiffusionXL: StarterModelBundle(name="SDXL", models=sdxl_bundle),
    BaseModelType.Flux: StarterModelBundle(name="FLUX.1 dev", models=flux_bundle),
    BaseModelType.Flux2: StarterModelBundle(name="FLUX.2 Klein", models=flux2_klein_bundle),
    BaseModelType.ZImage: StarterModelBundle(name="Z-Image Turbo", models=zimage_bundle),
    BaseModelType.ErnieImage: StarterModelBundle(name="ERNIE-Image", models=ernie_image_bundle),
    BaseModelType.QwenImage: StarterModelBundle(name="Qwen Image", models=qwen_image_bundle),
    BaseModelType.Anima: StarterModelBundle(name="Anima", models=anima_bundle),
    BaseModelType.Krea2: StarterModelBundle(name="Krea-2", models=krea2_bundle),
    "wan_t2v": StarterModelBundle(name="Wan 2.2 Text-to-Video", models=wan_t2v_bundle),
    "wan_i2v": StarterModelBundle(name="Wan 2.2 Image-to-Video", models=wan_i2v_bundle),
    BaseModelType.Ideogram4: StarterModelBundle(name="Ideogram 4", models=ideogram_bundle),
}


assert len(STARTER_MODELS) == len({m.source for m in STARTER_MODELS}), "Duplicate starter models"


__all__ = [
    "STARTER_BUNDLES",
    "STARTER_MODELS",
    "StarterModel",
    "StarterModelBundle",
    "StarterModelWithoutDependencies",
    "alibabacloud_qwen_image_2",
    "alibabacloud_qwen_image_2_pro",
    "alibabacloud_qwen_image_edit_max",
    "alibabacloud_qwen_image_max",
    "alibabacloud_wan26_t2i",
    "alien_lora_sdxl",
    "anima_base",
    "anima_lllite_depth_preview3",
    "anima_lllite_inpainting",
    "anima_lllite_lineart_preview3",
    "anima_lllite_pose_preview3",
    "anima_lllite_scribble_preview3",
    "anima_lllite_sketch",
    "anima_qwen3_encoder",
    "anima_vae",
    "animesharp_v4_rcan",
    "archvis_sdxl",
    "canny_sd1",
    "canny_sdxl",
    "clip_l_encoder",
    "clip_vit_l_image_encoder",
    "cogview4",
    "cyberrealistic_negative",
    "cyberrealistic_sd1",
    "deliberate_inpainting_sd1",
    "deliberate_sd1",
    "depth_sd1",
    "depth_sdxl",
    "dreamshaper_8_inpainting_sd1",
    "dreamshaper_8_sd1",
    "dreamshaper_sdxl",
    "easy_neg_sd1",
    "ernie_image",
    "ernie_image_turbo",
    "esrgan_srx4",
    "flux2_klein_4b",
    "flux2_klein_4b_fp8",
    "flux2_klein_4b_gguf_q4",
    "flux2_klein_4b_gguf_q8",
    "flux2_klein_4b_single",
    "flux2_klein_9b",
    "flux2_klein_9b_fp8",
    "flux2_klein_9b_gguf_q4",
    "flux2_klein_9b_gguf_q8",
    "flux2_klein_qwen3_4b_encoder",
    "flux2_klein_qwen3_8b_encoder",
    "flux2_vae",
    "flux_canny_control_lora",
    "flux_depth_control_lora",
    "flux_dev",
    "flux_dev_quantized",
    "flux_fill",
    "flux_kontext",
    "flux_kontext_quantized",
    "flux_krea",
    "flux_krea_quantized",
    "flux_redux",
    "flux_schnell",
    "flux_schnell_quantized",
    "flux_vae",
    "gemini_3_1_flash_image_preview",
    "gemini_flash_image",
    "gemini_pro_image_preview",
    "gemma2_2b_encoder",
    "ideogram_4_fp8",
    "ideogram_4_nf4",
    "inpaint_cnet_sd1",
    "ip_adapter_flux",
    "ip_adapter_plus_face_sd1",
    "ip_adapter_plus_sd1",
    "ip_adapter_plus_sdxl",
    "ip_adapter_sd1",
    "ip_adapter_sd_image_encoder",
    "ip_adapter_sdxl",
    "ip_adapter_sdxl_image_encoder",
    "juggernaut_sdxl",
    "krea2_raw",
    "krea2_turbo",
    "krea2_turbo_gguf_q4_k_m",
    "krea2_turbo_gguf_q8_0",
    "lineart_anime_sd1",
    "lineart_sd1",
    "llava_onevision",
    "llava_onevision_7b",
    "mlsd_sd1",
    "noodle_lora_sdxl",
    "normal_bae_sd1",
    "openai_dall_e_3",
    "openai_gpt_image_1",
    "openai_gpt_image_1_5",
    "openai_gpt_image_1_mini",
    "openai_gpt_image_2",
    "openpose_sd1",
    "openpose_sdxl",
    "pid_decoder_flux2_2k",
    "pid_decoder_flux2_2kto4k",
    "pid_decoder_flux_2k",
    "pid_decoder_flux_2kto4k",
    "pid_decoder_qwenimage_2kto4k",
    "pid_decoder_sd3_2k",
    "pid_decoder_sd3_2kto4k",
    "pid_decoder_sdxl_2kto4k",
    "qr_code_cnet_sd1",
    "qr_code_cnet_sdxl",
    "qwen2_5_1_5b_instruct",
    "qwen2_5_3b_instruct",
    "qwen3_vl_encoder_4b",
    "qwen_image",
    "qwen_image_edit",
    "qwen_image_edit_gguf_q2_k",
    "qwen_image_edit_gguf_q4_k_m",
    "qwen_image_edit_gguf_q6_k",
    "qwen_image_edit_gguf_q8_0",
    "qwen_image_edit_lightning_4step",
    "qwen_image_edit_lightning_8step",
    "qwen_image_gguf_q2_k",
    "qwen_image_gguf_q4_k_m",
    "qwen_image_gguf_q6_k",
    "qwen_image_gguf_q8_0",
    "qwen_image_lightning_4step",
    "qwen_image_lightning_8step",
    "qwen_image_vae",
    "qwen_vl_encoder_diffusers",
    "qwen_vl_encoder_fp8",
    "realesrgan_x2",
    "realesrgan_x4",
    "rev_animated_sd1",
    "scribble_sd1",
    "scribble_sdxl",
    "sd35_large",
    "sd35_medium",
    "sdxl_fp16_vae_fix",
    "sdxl_refiner",
    "seedream_4_0",
    "seedream_4_5",
    "seedream_5_0",
    "seedream_5_0_lite",
    "seg_sd1",
    "shuffle_sd1",
    "siglip",
    "smollm2_1_7b_instruct",
    "softedge_sd1",
    "softedge_sdxl",
    "swinir",
    "t2i_canny_sd1",
    "t2i_canny_sdxl",
    "t2i_depth_sd1",
    "t2i_lineart_sdxl",
    "t2i_sketch_sd1",
    "t2i_sketch_sdxl",
    "t5_8b_quantized_encoder",
    "t5_base_encoder",
    "t5_gguf_q3_k_s_encoder",
    "t5_gguf_q6_k_encoder",
    "tile_sd1",
    "tile_sdxl",
    "union_cnet_flux",
    "union_cnet_sdxl",
    "wan_22_5b_vae",
    "wan_22_a14b_vae",
    "wan_22_i2v_a14b_diffusers",
    "wan_22_i2v_a14b_gguf_q4_k_m",
    "wan_22_i2v_a14b_gguf_q8_0",
    "wan_22_i2v_a14b_low_gguf_q4_k_m",
    "wan_22_i2v_a14b_low_gguf_q8_0",
    "wan_22_i2v_lightning_high",
    "wan_22_i2v_lightning_low",
    "wan_22_t2v_a14b_diffusers",
    "wan_22_t2v_a14b_gguf_q4_k_m",
    "wan_22_t2v_a14b_gguf_q8_0",
    "wan_22_t2v_a14b_low_gguf_q4_k_m",
    "wan_22_t2v_a14b_low_gguf_q8_0",
    "wan_22_t2v_lightning_high",
    "wan_22_t2v_lightning_low",
    "wan_22_t5_encoder",
    "wan_22_ti2v_5b_diffusers",
    "wan_22_ti2v_5b_gguf_q4_k_m",
    "wan_22_ti2v_5b_gguf_q8_0",
    "z_image_controlnet_tile",
    "z_image_controlnet_union",
    "z_image_qwen3_encoder",
    "z_image_qwen3_encoder_quantized",
    "z_image_turbo",
    "z_image_turbo_q8",
    "z_image_turbo_quantized",
]
