/**
 * The per-base capability table webv2 ships, written out for the backend to check itself against.
 *
 * `BASE_GENERATION` and `invokeai/backend/architectures/defs/<base>.py` state the same facts about
 * the same architectures: the dimension grid, which scheduler family applies and whether the choice
 * reaches the graph, what the guidance slider is called, whether the negative prompt is shown and
 * used, and which UI affordances exist. The frontend table is the one that ships behaviour; the
 * backend one is what `GET /api/v2/models/capabilities` serves. Neither can see the other, so they
 * drift silently — ERNIE-Image shipped with `scheduler_applies_to_graph` false on the backend and
 * true here, and nothing failed.
 *
 * This is the same cross-stack contract `graphCoverage.test.ts` already builds for node types:
 * generated here from the real module (no parsing), consumed by
 * `tests/backend/architectures/test_frontend_capability_parity.py`.
 *
 * `defaults` and `dimensions.optimalSide` are deliberately absent. Those genuinely differ by
 * design: the backend numbers are per-model card values delivered through `default_settings`, and
 * these are the fallback for when no model is selected. Recording them would assert a false
 * equivalence.
 *
 * Written by this test and by nothing else — `.oxfmtrc.json` excludes it, as it does the other one.
 */

import { describe, expect, it } from 'vitest';

import type { BaseGenerationConfig, SupportedGenerateBase } from './baseGenerationPolicies';

import { BASE_GENERATION, SUPPORTED_GENERATE_BASES } from './baseGenerationPolicies';

describe('base capability contract', () => {
  it('emits the per-base facts the backend declares too', async () => {
    const byBase: Record<string, unknown> = {};

    for (const base of [...SUPPORTED_GENERATE_BASES].sort()) {
      // Typed through the declared interface: the literal object narrows `ui.clipSkipMax` away
      // for the bases that omit it, which would make this read only the bases that have one.
      const config: BaseGenerationConfig = BASE_GENERATION[base as SupportedGenerateBase];

      byBase[base] = {
        dimensionGrid: config.dimensions.grid,
        guidanceLabel: config.guidanceLabel,
        negativePrompt: config.negativePrompt,
        schedulerAppliesToGraph: config.schedulerAppliesToGraph,
        schedulerSet: config.schedulerSet,
        ui: {
          cfgRescale: config.ui.cfgRescale,
          clipSkipMax: config.ui.clipSkipMax ?? null,
          colorCompensation: config.ui.colorCompensation,
          sdVaeOverride: config.ui.sdVaeOverride,
          seamless: config.ui.seamless,
          vaePrecision: config.ui.vaePrecision,
        },
      };
    }

    const contract = {
      _comment:
        'Generated by src/features/generation/core/capabilityContract.test.ts; regenerate with ' +
        '`vitest -u`. Excluded from oxfmt so the test alone owns its layout. Consumed by ' +
        'tests/backend/architectures/test_frontend_capability_parity.py, which checks every value ' +
        'below against the architecture registry.',
      byBase,
    };

    await expect(`${JSON.stringify(contract, null, 2)}\n`).toMatchFileSnapshot(
      './__snapshots__/baseGenerationCapabilities.json'
    );
  });
});
